export const roles = {
    admin: "Admin",
    managingDirector: "Managing Director",
    executiveLeadership: 'Executive Leadership',
    generalUser: "General User",
    gmc: "GMC",
    marketingExecutive: "Marketing Executive",
    managerCommerical: "Manager Commercial",
    commercialExecutive: "Commercial Executive",
    asstManagerPurchase: "Assistant Manager Purchase GC",
    managerPurchaseGC: "Manager Purchase GC",
    managerStoresPackingAndGC: "Manager Stores Packing and GC",
    purchaseExecutiveGC: "Purchase Executive GC",
    gcStoresExecutive: "GC Stores Executive",
    srManager: "Sr.Manager",
    qcManager: "QC Manager",
    accountsExecutive: "Accounts Executive",
    accountsManager: "Accounts Manager",
    vendor: "Vendor",
    marketingRepresentative: "Marketing Representative",
    managerPackagingDevelopment: "Manager Packaging Development",
    purchaseManager: "Purchase Manager",
    managerPurchaseGCQuotes: "Manager Purchase GC-Quotes",
    managerPurchasePackaging: "Manager Purchase Packaging",
    BusinessDevelopmentManager: "Business Development Manager",
    packingExecutive: "Packing Executive",
    purchaseExecutiveME: "Purchase Executive M&E",
}

export const routes = {
    settings: '/settings',
    home: '/home',
    leads: '/leads',
    createLead: '/leads/create',
    editLead: '/leads/:leadId/edit',
    viewLead: '/leads/:leadId/view',
    deleteLead: '/leads/:leadId/delete',
    accounts: '/accounts',
    viewAccount: '/accounts/:accountId/view',
    editAccount: '/accounts/:accountId/edit',
    createContact: '/accounts/:accountId/contacts/create',
    createSampleRequestFromAccount: '/accounts/:accountId/sample-request/create',
    createQuoteFromAccount: '/accounts/:accountId/quote/create',
    contacts: '/contacts',
    viewContact: '/contacts/:contactId/view',
    editContact: '/contacts/:contactId/edit',
    addBillingAddressOnContact: '/contacts/:accountId/:contactId/billingAddress/add',
    viewBillingAddressOnContact: '/contacts/:accountId/:contactId/:billingId/billingAddress/view',
    viewshippingAddressOnContact: '/contacts/:accountId/:contactId/:shippingId/shippingAddress/view',
    addShippingAddressOnContact: '/contacts/:accountId/:contactId/shippingAddress/add',
    editBillingAddressOnContact: '/contacts/:accountId/:contactId/billingAddress/edit',
    editShippingAddressOnContact: '/contacts/:accountId/:contactId/shippingAddress/edit',
    sampleRequest: '/sample-request',
    createSampleRequest: '/sample-request/create',
    viewSampleRequest: '/sample-request/:sampleId/view',
    editSampleRequest: '/sample-request/:sampleId/edit',
    addSampleItem: '/sample-request/:sampleId/sample-item/create',
    viewSampleItem: '/sample-request/:sampleId/sample-item/:sampleItemId/view',
    editSampleItem: '/sample-request/:sampleId/sample-item/:sampleItemId/edit',
    quote: '/quote',
    createQuote: '/quote/create',
    editQuote: '/quote/:quoteId/edit',
    viewQuote: '/quote/:quoteId/view',
    createQuoteItem: '/quote-item/:accountId/:quoteId/:quoteNumber/create',
    viewQuoteItem: '/quote-item/:accountId/:quoteItemId/view',
    viewPendingQuoteItem: '/quote-item/:quoteItemId/view',
    editQuoteItem: '/quote-item/:accountId/:quoteId/:quoteItemId/edit',
    users: '/users',
    createUser: '/users/create',
    viewUser: '/users/:userId/view',
    editUser: '/users/:userId/edit',
    purchaseOrders: '/purchase-orders',
    createPurchaseOrder: '/purchase-order/create',
    viewPurchaseOrder: '/purchase-order/:poid/view',
    editPurchaseOrder: '/purchase-order/:poid/edit',
    viewDispatch: '/purchase-order/:poid/dispatch/:dispatchId/view',
    debitNoteGC: '/debit-note-gc',
    createDebitNoteGC: '/debit-note-gc/create',
    viewDebitNoteGC: '/debit-note-gc/:debitNoteId/view',
    editDebitNoteGC: '/debit-note-gc/:debitNoteId/edit',
    mrin: '/mrin',
    createMRIN: '/mrin/create',
    editMRIN: '/mrin/:mrinId/edit',
    viewMRIN: '/mrin/:mrinId/view',
    gc: '/gc',
    createGC: '/gc/create',
    editGC: '/gc/:gcId/edit',
    viewGC: '/gc/:gcId/view',
    supplier: '/supplier',
    createSupplier: '/supplier/create',
    editSupplier: '/supplier/:supplierId/edit',
    viewSupplier: '/supplier/:supplierId/view',
    packingType: '/packing-type',
    login: '/login',
    vendor: '/vendor',
    vendorLogin: '/login/vendor',
    forget: '/forget',
    packaging: '/packaging',
    viewPackaging: '/packaging/:packagingId/view',


}


export const roleBasedRoutes = {
    [roles.admin]: [routes.users, routes.createUser, routes.viewUser, routes.editUser, routes.settings],
    [roles.managingDirector]: [routes.leads, routes.createLead, routes.editLead, routes.deleteLead,
    routes.viewLead,
    routes.users, routes.createUser, routes.editUser, routes.viewUser, routes.accounts, routes.createContact, routes.createSampleRequestFromAccount, routes.createQuoteFromAccount,
    routes.viewAccount, routes.editAccount,
    routes.contacts, routes.addBillingAddressOnContact, routes.addShippingAddressOnContact, routes.viewBillingAddressOnContact, routes.viewshippingAddressOnContact, routes.viewContact, routes.editContact, routes.sampleRequest, routes.createSampleRequest, routes.editSampleRequest, routes.addSampleItem, routes.viewSampleItem, routes.editSampleItem, routes.viewSampleRequest,
    // routes.samples, 
    routes.quote, routes.createQuote, routes.viewQuote, routes.editQuote, routes.createQuoteItem, routes.editQuoteItem, routes.viewQuoteItem, routes.viewPendingQuoteItem, routes.purchaseOrders, routes.createPurchaseOrder, routes.viewPurchaseOrder, routes.viewDispatch, routes.editPurchaseOrder, routes.debitNoteGC, routes.viewDebitNoteGC, routes.editDebitNoteGC, routes.createDebitNoteGC, routes.mrin, routes.createMRIN, routes.editMRIN,
    routes.viewMRIN, routes.gc, routes.supplier,
    routes.createSupplier, routes.editSupplier, routes.viewSupplier,
    routes.createGC, routes.editGC, routes.viewGC],
    [roles.executiveLeadership]: [routes.leads, routes.createLead, routes.editLead, routes.deleteLead,
    routes.viewLead,
    routes.users, routes.createUser, routes.editUser, routes.viewUser, routes.accounts, routes.createContact, routes.createSampleRequestFromAccount, routes.createQuoteFromAccount,
    routes.viewAccount, routes.editAccount,
    routes.contacts, routes.addBillingAddressOnContact, routes.addShippingAddressOnContact, routes.viewBillingAddressOnContact, routes.viewshippingAddressOnContact, routes.viewContact, routes.editContact, routes.sampleRequest, routes.createSampleRequest, routes.editSampleRequest, routes.addSampleItem, routes.viewSampleItem, routes.editSampleItem, routes.viewSampleRequest,
    // routes.samples, 
    routes.quote, routes.createQuote, routes.viewQuote, routes.editQuote, routes.createQuoteItem, routes.editQuoteItem, routes.viewQuoteItem, routes.viewPendingQuoteItem, routes.purchaseOrders, routes.createPurchaseOrder, routes.viewPurchaseOrder, routes.viewDispatch, routes.editPurchaseOrder, routes.debitNoteGC, routes.viewDebitNoteGC, routes.editDebitNoteGC, routes.createDebitNoteGC, routes.mrin, routes.createMRIN, routes.editMRIN,
    routes.viewMRIN, routes.gc, routes.supplier,
    routes.createSupplier, routes.editSupplier, routes.viewSupplier,
    routes.createGC, routes.editGC, routes.viewGC],
    [roles.gmc]: [routes.quote,],
    [roles.marketingExecutive]: [routes.leads, routes.createLead, routes.editLead, routes.viewLead,
    routes.deleteLead, routes.accounts, routes.createContact, routes.createSampleRequestFromAccount, routes.createQuoteFromAccount, routes.viewAccount, routes.editAccount,
    routes.sampleRequest, routes.createSampleRequest, routes.editSampleRequest, routes.addSampleItem, routes.viewSampleItem, routes.editSampleItem, routes.viewSampleRequest,
    routes.packaging, routes.viewPackaging,
    // routes.samples,
    routes.quote, routes.createQuote, routes.viewQuote, routes.editQuote, routes.createQuoteItem, routes.editQuoteItem, routes.viewBillingAddressOnContact, routes.viewshippingAddressOnContact, routes.viewQuoteItem, routes.viewPendingQuoteItem, routes.contacts, routes.addBillingAddressOnContact, routes.addShippingAddressOnContact, routes.viewContact, routes.editContact],
    [roles.managerCommerical]: [],
    [roles.commercialExecutive]: [routes.quotes],

    [roles.qcManager]: [routes.mrin, routes.createMRIN, routes.viewMRIN, routes.editMRIN, routes.packaging, routes.viewPackaging],
    [roles.BusinessDevelopmentManager]: [routes.quote, routes.createQuote, routes.viewQuote, routes.editQuote, routes.createQuoteItem, routes.editQuoteItem, routes.viewQuoteItem, routes.viewPendingQuoteItem, routes.leads, routes.accounts, routes.createContact, routes.createSampleRequestFromAccount, routes.createQuoteFromAccount, routes.contacts, routes.addBillingAddressOnContact, routes.addShippingAddressOnContact, routes.viewBillingAddressOnContact, routes.viewshippingAddressOnContact, routes.viewContact, routes.editContact, routes.sampleRequest, routes.createSampleRequest, routes.editSampleRequest, routes.addSampleItem, routes.viewSampleItem, routes.editSampleItem, routes.viewSampleRequest, routes.createLead],
    [roles.asstManagerPurchase]: [routes.home, routes.quote, routes.createQuote, routes.viewQuote, routes.editQuote, routes.createQuoteItem, routes.editQuoteItem, routes.viewQuoteItem, routes.viewPendingQuoteItem, routes.purchaseOrders, routes.createPurchaseOrder, routes.viewPurchaseOrder, routes.viewDispatch, routes.editPurchaseOrder,],
    [roles.managerPurchaseGC]: [routes.home, routes.debitNoteGC, routes.viewDebitNoteGC, routes.editDebitNoteGC, routes.createDebitNoteGC, routes.quote, routes.createQuote, routes.viewQuote, routes.editQuote, routes.createQuoteItem, routes.editQuoteItem, routes.viewQuoteItem, routes.viewPendingQuoteItem, routes.purchaseOrders, routes.createPurchaseOrder, routes.viewPurchaseOrder, routes.viewDispatch, routes.editPurchaseOrder, routes.mrin, routes.createMRIN,
    routes.editMRIN, routes.viewMRIN, routes.gc,
    routes.supplier, routes.createSupplier, routes.editSupplier, routes.viewSupplier, routes.createGC, routes.viewGC, routes.editGC],
    [roles.managerStoresPackingAndGC]: [routes.purchaseOrders, routes.createPurchaseOrder, routes.viewPurchaseOrder, routes.viewDispatch, routes.editPurchaseOrder, routes.mrin, routes.createMRIN, routes.editMRIN,
    routes.viewMRIN, routes.gc, routes.createGC, routes.editGC, routes.viewGC],
    [roles.purchaseExecutiveGC]: [routes.purchaseOrders, routes.createPurchaseOrder, routes.viewPurchaseOrder, routes.viewDispatch, routes.editPurchaseOrder, routes.home],
    [roles.gcStoresExecutive]: [routes.purchaseOrders, routes.createPurchaseOrder, routes.viewPurchaseOrder, routes.viewDispatch, routes.editPurchaseOrder, routes.mrin, routes.createMRIN, routes.editMRIN, routes.viewMRIN,
    routes.gc, routes.createGC, routes.viewGC, routes.editGC],
    [roles.srManager]: [routes.mrin, routes.createMRIN, routes.editMRIN, routes.viewMRIN],
    [roles.accountsExecutive]: [routes.mrin, routes.createMRIN, routes.editMRIN, routes.viewMRIN,
    routes.purchaseOrders, routes.createPurchaseOrder, routes.viewPurchaseOrder, routes.viewDispatch, routes.editPurchaseOrder, routes.debitNoteGC, routes.viewDebitNoteGC, routes.editDebitNoteGC, routes.createDebitNoteGC],
    [roles.accountsManager]: [routes.purchaseOrders, routes.createPurchaseOrder, routes.viewPurchaseOrder, routes.viewDispatch, routes.editPurchaseOrder, routes.debitNoteGC, routes.viewDebitNoteGC, routes.editDebitNoteGC, routes.createDebitNoteGC, routes.mrin, routes.createMRIN, routes.viewMRIN,
    routes.editMRIN],
    [roles.vendor]: [routes.vendor],
    [roles.marketingRepresentative]: [],
    [roles.generalUser]: [],
    [roles.managerPackagingDevelopment]: [],
    [roles.purchaseManager]: [routes.supplier, routes.createSupplier, routes.viewSupplier, routes.editSupplier],
    [roles.managerPurchaseGCQuotes]: [routes.quote, routes.viewQuote, routes.editQuote, routes.viewQuoteItem, routes.viewPendingQuoteItem, routes.editQuoteItem],
    [roles.managerPurchasePackaging]: [routes.packaging, routes.viewPackaging],
    [roles.packingExecutive]: [routes.quote, routes.viewQuote, routes.editQuote, routes.viewQuoteItem, routes.viewPendingQuoteItem, routes.editQuoteItem],
    [roles.purchaseExecutiveME]: [routes.supplier, routes.createSupplier, routes.viewSupplier, routes.editSupplier],
}
export default roles;
